export const cities = [
  {
    fullName: 'Acton Movers',
    shortName: 'Acton',
    state: 'MA',
    description: '',
    slug: 'Acton-Movers',
    icon: '',
  },
  {
    fullName: 'Boston Movers',
    shortName: 'Boston',
    state: 'MA',
    description: '',
    slug: 'Boston-Movers',
    icon: '',
  },
  {
    fullName: 'Cambridge Movers',
    shortName: 'Cambridge',
    state: 'MA',
    description: '',
    slug: 'Cambridge-Movers',
    icon: '',
  },
  {
    fullName: 'Waltham Movers',
    shortName: 'Waltham',
    state: 'MA',
    description: '',
    slug: 'Waltham-Movers',
    icon: '',
  },
  {
    fullName: 'Burlington Movers',
    shortName: 'Burlington',
    state: 'MA',
    description: '',
    slug: 'Burlington-Movers',
    icon: '',
  },
  {
    fullName: 'Woburn Movers',
    shortName: 'Woburn',
    state: 'MA',
    description: '',
    slug: 'Woburn-Movers',
    icon: '',
  },
  {
    fullName: 'Newton Movers',
    shortName: 'Newton',
    state: 'MA',
    description: '',
    slug: 'Newton-Movers',
    icon: '',
  },
  {
    fullName: 'Lexington Movers',
    shortName: 'Lexington',
    state: 'MA',
    description: '',
    slug: 'Lexington-Movers',
    icon: '',
  },
  {
    fullName: 'Wellesley Movers',
    shortName: 'Wellesley',
    state: 'MA',
    description: '',
    slug: 'Wellesley-Movers',
    icon: '',
  },
  {
    fullName: 'Framingham Movers',
    shortName: 'Framingham',
    state: 'MA',
    description: '',
    slug: 'Framingham-Movers',
    icon: '',
  },
  {
    fullName: 'Marlborough Movers',
    shortName: 'Marlborough',
    state: 'MA',
    description: '',
    slug: 'Marlborough-Movers',
    icon: '',
  },
  {
    fullName: 'Bedford Movers',
    shortName: 'Bedford',
    state: 'MA',
    description: '',
    slug: 'Bedford-Movers',
    icon: '',
  },
  {
    fullName: 'Somerville Movers',
    shortName: 'Somerville',
    state: 'MA',
    description: '',
    slug: 'Somerville-Movers',
    icon: '',
  },
  {
    fullName: 'Andover Movers',
    shortName: 'Andover',
    state: 'MA',
    description: '',
    slug: 'Andover-Movers',
    icon: '',
  },
  {
    fullName: 'Needham Movers',
    shortName: 'Needham',
    state: 'MA',
    description: '',
    slug: 'Needham-Movers',
    icon: '',
  },
  {
    fullName: 'Watertown Movers',
    shortName: 'Watertown',
    state: 'MA',
    description: '',
    slug: 'Watertown-Movers',
    icon: '',
  },
  {
    fullName: 'Concord Movers',
    shortName: 'Concord',
    state: 'MA',
    description: '',
    slug: 'Concord-Movers',
    icon: '',
  },
  {
    fullName: 'Quincy Movers',
    shortName: 'Quincy',
    state: 'MA',
    description: '',
    slug: 'Quincy-Movers',
    icon: '',
  },
  {
    fullName: 'Billerica Movers',
    shortName: 'Billerica',
    state: 'MA',
    description: '',
    slug: 'Billerica-Movers',
    icon: '',
  },
  {
    fullName: 'Brookline Movers',
    shortName: 'Brookline',
    state: 'MA',
    description: '',
    slug: 'Brookline-Movers',
    icon: '',
  },
  {
    fullName: 'Natick Movers',
    shortName: 'Natick',
    state: 'MA',
    description: '',
    slug: 'Natick-Movers',
    icon: '',
  },
  {
    fullName: 'Medford Movers',
    shortName: 'Medford',
    state: 'MA',
    description: '',
    slug: 'Medford-Movers',
    icon: '',
  },
  {
    fullName: 'Canton Movers',
    shortName: 'Canton',
    state: 'MA',
    description: '',
    slug: 'Canton-Movers',
    icon: '',
  },
  {
    fullName: 'Maynard Movers',
    shortName: 'Maynard',
    state: 'MA',
    description: '',
    slug: 'Maynard-Movers',
    icon: '',
  },
  {
    fullName: 'Andover Movers',
    shortName: 'Andover',
    state: 'MA',
    description: '',
    slug: 'Andover-Movers',
    icon: '',
  },
  {
    fullName: 'Westwood Movers',
    shortName: 'Westwood',
    state: 'MA',
    description: '',
    slug: 'Westwood-Movers',
    icon: '',
  },
  {
    fullName: 'Salem Movers',
    shortName: 'Salem',
    state: 'MA',
    description: '',
    slug: 'Salem-Movers',
    icon: '',
  },
  {
    fullName: 'Braintree Movers',
    shortName: 'Braintree',
    state: 'MA',
    description: '',
    slug: 'Braintree-Movers',
    icon: '',
  },
  {
    fullName: 'Charlestown Movers',
    shortName: 'Charlestown',
    state: 'MA',
    description: '',
    slug: 'Charlestown-Movers',
    icon: '',
  },
  {
    fullName: 'Danvers Movers',
    shortName: 'Danvers',
    state: 'MA',
    description: '',
    slug: 'Danvers-Movers',
    icon: '',
  },
  {
    fullName: 'Norwood Movers',
    shortName: 'Norwood',
    state: 'MA',
    description: '',
    slug: 'Norwood-Movers',
    icon: '',
  },
  {
    fullName: 'Sudbury Movers',
    shortName: 'Sudbury',
    state: 'MA',
    description: '',
    slug: 'Sudbury-Movers',
    icon: '',
  },
  {
    fullName: 'Franklin Movers',
    shortName: 'Franklin',
    state: 'MA',
    description: '',
    slug: 'Franklin-Movers',
    icon: '',
  },
  {
    fullName: 'Dedham Movers',
    shortName: 'Dedham',
    state: 'MA',
    description: '',
    slug: 'Dedham-Movers',
    icon: '',
  },
  {
    fullName: 'Belmont Movers',
    shortName: 'Belmont',
    state: 'MA',
    description: '',
    slug: 'Belmont-Movers',
    icon: '',
  },
  {
    fullName: 'Allston Movers',
    shortName: 'Allston',
    state: 'MA',
    description: '',
    slug: 'Allston-Movers',
    icon: '',
  },
  {
    fullName: 'Newburyport Movers',
    shortName: 'Newburyport',
    state: 'MA',
    description: '',
    slug: 'Newburyport-Movers',
    icon: '',
  },
  {
    fullName: 'Wayland Movers',
    shortName: 'Wayland',
    state: 'MA',
    description: '',
    slug: 'Wayland-Movers',
    icon: '',
  },
  {
    fullName: 'Cape Cod Movers',
    shortName: 'Cape Cod',
    state: 'MA',
    description: '',
    slug: 'Cape-Cod-Movers',
    icon: '',
  },
  {
    fullName: 'Peabody Movers',
    shortName: 'Peabody',
    state: 'MA',
    description: '',
    slug: 'Peabody-Movers',
    icon: '',
  },
  {
    fullName: 'Weymouth Movers',
    shortName: 'Weymouth',
    state: 'MA',
    description: '',
    slug: 'Weymouth-Movers',
    icon: '',
  },
  {
    fullName: 'Lincoln Movers',
    shortName: 'Lincoln',
    state: 'MA',
    description: '',
    slug: 'Lincoln-Movers',
    icon: '',
  },
  {
    fullName: 'Brighton Movers',
    shortName: 'Brighton',
    state: 'MA',
    description: '',
    slug: 'Brighton-Movers',
    icon: '',
  },
  {
    fullName: 'Dover Movers',
    shortName: 'Dover',
    state: 'MA',
    description: '',
    slug: 'Dover-Movers',
    icon: '',
  },
  {
    fullName: 'Holliston Movers',
    shortName: 'Holliston',
    state: 'MA',
    description: '',
    slug: 'Holliston-Movers',
    icon: '',
  },
  {
    fullName: 'Malden Movers',
    shortName: 'Malden',
    state: 'MA',
    description: '',
    slug: 'Malden-Movers',
    icon: '',
  },
  {
    fullName: 'Foxboro Movers',
    shortName: 'Foxboro',
    state: 'MA',
    description: '',
    slug: 'Foxboro-Movers',
    icon: '',
  },
  {
    fullName: 'Reading Movers',
    shortName: 'Reading',
    state: 'MA',
    description: '',
    slug: 'Reading-Movers',
    icon: '',
  },
  {
    fullName: 'Walpole Movers',
    shortName: 'Walpole',
    state: 'MA',
    description: '',
    slug: 'Walpole-Movers',
    icon: '',
  },
  {
    fullName: 'Winchester Movers',
    shortName: 'Winchester',
    state: 'MA',
    description: '',
    slug: 'Winchester-Movers',
    icon: '',
  },
  {
    fullName: 'Arlington Movers',
    shortName: 'Arlington',
    state: 'MA',
    description: '',
    slug: 'Arlington-Movers',
    icon: '',
  },
  {
    fullName: 'Millis Movers',
    shortName: 'Millis',
    state: 'MA',
    description: '',
    slug: 'Millis-Movers',
    icon: '',
  },
  {
    fullName: 'Sharon Movers',
    shortName: 'Sharon',
    state: 'MA',
    description: '',
    slug: 'Sharon-Movers',
    icon: '',
  },
  {
    fullName: 'Norfolk Movers',
    shortName: 'Norfolk',
    state: 'MA',
    description: '',
    slug: 'Norfolk-Movers',
    icon: '',
  },
  {
    fullName: 'Rhode Island Movers',
    shortName: 'Rhode Island',
    state: 'RI',
    description: '',
    slug: 'Rhode-Island-Movers',
    icon: '',
  },
  {
    fullName: 'New Hampshire Movers',
    shortName: 'New Hampshire',
    state: 'NH',
    description: '',
    slug: 'New-Hampshire-Movers',
    icon: '',
  },
  {
    fullName: 'Vermont Movers',
    shortName: 'Vermont',
    state: 'VT',
    description: '',
    slug: 'Vermont-Movers',
    icon: '',
  },
  {
    fullName: 'Albany Movers',
    shortName: 'Albany',
    state: 'NY',
    description: '',
    slug: 'Albany-Movers',
    icon: '',
  },
];
