import submitFormModel from './submitFormModel';
const {
  formField: {
    firstName,
    lastName,
    email,
    phone,
    moveDate,
    deliveryDate,
    startTime,
    origin,
    destination,
    service,
    size,
    additionalInfo,
    // address1,
    // city,
    // zipcode,
    // country,
    // useAddressForPaymentDetails,
    // nameOnCard,
    // cardNumber,
    // expiryDate,
    // cvv,
  },
} = submitFormModel;

export default {
  [firstName.name]: 'Serg',
  [lastName.name]: 'Frunza',
  [email.name]: 'frunza.sergiu3@gmail.com',
  [phone.name]: '(617) 206-0968',
  [moveDate.name]: '',
  [deliveryDate.name]: '',
  [startTime.name]: 'Any time',
  [service.name]: 'moving',
  [size.name]: '',
  [additionalInfo.name]: '',
  origin: {
    address: '',
    city: '',
    state: '',
    zip: '02026',
    floor: 'house',
    apt: '',
  },
  destination: {
    address: '',
    city: '',
    state: '',
    zip: '02446',
    floor: 'elevator',
    apt: '',
  },
  //   [address1.name]: '',
  //   [city.name]: '',
  //   [zipcode.name]: '',
  //   [country.name]: '',
  //   [useAddressForPaymentDetails.name]: false,
  //   [nameOnCard.name]: '',
  //   [cardNumber.name]: '',
  //   [expiryDate.name]: '',
  //   [cvv.name]: '',
};
